<?php include 'includes/header.php'; ?>
    <div class="blog-post">
        <h2 class="blog-post-title">International PHP Conference</h2>
        <p class="blog-post-meta">January 1, 2014 by <a href="#">Mark</a></p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis et convallis ante, in rhoncus lacus. Sed vehicula, tortor sed sodales rhoncus, libero lorem feugiat diam, posuere porta tellus risus non libero. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis metus felis, bibendum in tortor a, elementum tempor sapien. Aliquam rhoncus erat quis enim accumsan placerat. Pellentesque mi quam, accumsan et tellus eget, gravida iaculis ipsum. Nulla cursus nec nisi at luctus. Aenean eget commodo erat, sit amet elementum magna. Praesent at libero volutpat, porta purus eu, maximus erat. Maecenas tristique id lacus at sollicitudin. Mauris ut mollis est, et laoreet sem. Etiam vitae leo a orci pretium pretium.</p>
        <p>Ut vel tortor at arcu interdum maximus. Pellentesque euismod porttitor enim, lobortis ultricies tellus mollis ut. Integer quis porttitor augue. Curabitur aliquam finibus egestas. Aliquam et odio id justo tincidunt congue. Phasellus ultrices tincidunt tellus a auctor. Vestibulum sagittis magna purus, finibus maximus ipsum dictum scelerisque. Mauris a massa a nisl interdum semper eget at enim. Mauris molestie metus sollicitudin nunc malesuada, quis condimentum arcu mollis. Donec posuere molestie commodo. Phasellus sed nunc mauris. Curabitur consequat et est eget tincidunt.</p>
        <p>Nunc tristique nisi massa, sit amet maximus diam vehicula et. Pellentesque vehicula, sem a iaculis feugiat, leo purus vehicula diam, id laoreet risus mauris sed nunc. Duis sit amet diam sit amet lorem tempor fermentum quis eget libero. In id gravida enim. Suspendisse condimentum lobortis lacus eget gravida. Nullam pretium justo venenatis, pretium tellus eleifend, venenatis enim. Fusce efficitur purus felis, sit amet laoreet libero hendrerit id. Donec faucibus laoreet mollis. Maecenas dolor quam, eleifend vitae nunc non, ornare vestibulum lacus. Phasellus laoreet, sapien vitae dictum scelerisque, dui nunc pulvinar eros, sed euismod lorem erat sit amet odio. Fusce vitae dolor erat. Ut vel lacus massa. Donec varius ligula in diam varius, et mattis risus rhoncus. Praesent volutpat, quam pretium volutpat lacinia, eros sem malesuada lacus, at fringilla enim dui sit amet turpis. Sed rutrum risus dui, ut pellentesque turpis fermentum et.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis et convallis ante, in rhoncus lacus. Sed vehicula, tortor sed sodales rhoncus, libero lorem feugiat diam, posuere porta tellus risus non libero. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis metus felis, bibendum in tortor a, elementum tempor sapien. Aliquam rhoncus erat quis enim accumsan placerat. Pellentesque mi quam, accumsan et tellus eget, gravida iaculis ipsum. Nulla cursus nec nisi at luctus. Aenean eget commodo erat, sit amet elementum magna. Praesent at libero volutpat, porta purus eu, maximus erat. Maecenas tristique id lacus at sollicitudin. Mauris ut mollis est, et laoreet sem. Etiam vitae leo a orci pretium pretium.</p>
        <a class="readmore" href="post.php?id=1">Read More</a>
    </div><!-- /.blog-post -->
<?php include 'includes/footer.php'; ?>